name: security
on:
  workflow_dispatch:
permissions:
  actions: read
  security-events: write
  contents: read
jobs:
  dependencies-analysis:
    name: Dependencies Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@c51854704019a247608d928f370c98740469d4b5
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true
      - name: Upload SARIF to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: DependenciesAnalysisFull.sarif
          category: dependencies
  source-code-analysis:
    name: Source Code Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:34b079df03bd8ed6860552adf3905cc5d146dc4d
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          semgrep scan \
            --config .semgrep \
            --sarif \
            --output SourceCodeAnalysis.sarif
        continue-on-error: true
      - name: Upload SARIF to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: SourceCodeAnalysis.sarif
          category: source-code
